services:
    questdb:
        image: questdb/questdb
        container_name: questdb
        restart: always
        ports:
            - "9000:9000"
            - "9009:9009"
            - "8812:8812"
        volumes:
            - ./config/questdb:/var/lib/questdb/conf

    prometheus:
        image: prom/prometheus
        container_name: prometheus
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.console.libraries=/etc/prometheus/console_libraries"
            - "--web.console.templates=/etc/prometheus/consoles"
            - "--storage.tsdb.retention.time=200h"
            - "--web.enable-lifecycle"
        volumes:
            - ../config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - "9090:9090"

    tempo:
        image: grafana/tempo
        container_name: tempo
        command: ["-config.file=/etc/tempo.yaml"]
        volumes:
            - ../config/tempo/tempo.yaml:/etc/tempo.yaml
        ports:
            - "3200:3200"

    otel-collector:
        image: otel/opentelemetry-collector-contrib
        container_name: otel-collector
        depends_on:
            - prometheus
            - tempo
        command: ["--config=/etc/otel-collector-config.yaml"]
        volumes:
            - ../config/otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
        ports:
            - "4317:4317" # OTLP gRPC receiver
            - "4318:4318" # OTLP HTTP receiver
            - "8889:8889" # Prometheus metrics endpoint

    grafana:
        image: grafana/grafana
        container_name: grafana
        depends_on:
            - tempo
            - prometheus
        user: "0"
        volumes:
            - ./config/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
            - ./config/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/main.yaml
            - ./config/grafana/dashboards/output:/var/lib/grafana/dashboards
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_AUTH_ANONYMOUS_ENABLED=false
            - GF_INSTALL_PLUGINS=questdb-questdb-datasource
            - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=250ms
        ports:
            - "3000:3000"
